# Для каждого монитора указываем обои
preload = ~/.config/hypr/wallpaper.jpg
wallpaper = ,~/.config/hypr/wallpaper.jpg
# Если нужно задать на конкретный монитор:
# wallpaper = DP-1,~/path/to/wallpaper.jpg
